import { Bot, CheckCircle2, Clock3, Eye, FileCheck2, MessageCircle, MoonStar, Tags } from 'lucide-react'
import { Link } from 'react-router-dom'

export function AboutPage() {
  return <>
    <section className="about-hero page-wrap"><span className="eyebrow">Om Ljusglimt</span><h1>Mer av det som fungerar.<br />Tydligare om hur vi vet.</h1><p>Ljusglimt är en nyhetssamling under utveckling. Den kombinerar svenska källsammanfattningar med automatiskt hämtade källnotiser och ett modererat forum.</p></section>
    <section className="about-principles page-wrap"><article><Eye /><span>01</span><h2>Transparens först</h2><p>Varje publicering visar källa, ursprung och vilken typ av text du läser.</p></article><article><Tags /><span>02</span><h2>Tydlig märkning</h2><p>“Sammanfattning av källan” och “Engelsk källnotis” betyder olika saker.</p></article><article><MessageCircle /><span>03</span><h2>Vänligare samtal</h2><p>Forumets bidrag förhandsmodereras innan de blir offentliga.</p></article></section>
    <section className="method-section" id="kallor"><div className="page-wrap"><header><span className="eyebrow">Så fungerar det</span><h2>Från källa till Ljusglimt</h2></header><div className="method-steps"><article><span>1</span><MoonStar /><h3>Två dagliga hämtningar</h3><p>Källflöden söks igenom automatiskt klockan 00:00 och 12:00 svensk tid. Poster sparas med sin ursprungslänk.</p></article><article><span>2</span><Bot /><h3>Automatisk sortering</h3><p>Positiva signaler prioriteras och känsliga ämnen filtreras bort. Automatiken är ett urvalsstöd, inte en garanti om faktagranskning.</p></article><article><span>3</span><FileCheck2 /><h3>Tydlig publicering</h3><p>Källnotiser och svenska källsammanfattningar märks tydligt och leder vidare till originalkällan.</p></article></div></div></section>
    <section className="source-explainer page-wrap"><div><span className="eyebrow">Innehåll och bilder</span><h2>Vad betyder märkningen?</h2></div><div><article><strong>Sammanfattning av källan</strong><p>Vissa nyheter sammanfattas automatiskt från länkade källor. Originalkällan finns alltid tillgänglig.</p></article><article><strong>Engelsk källnotis</strong><p>Rubrik och utdrag från det automatiska flödet. Hela sammanhanget finns på källsidan och kan vara på engelska.</p></article><article><strong>AI-illustration</strong><p>Om en källbild saknar verifierad användningsrätt skapas en unik redaktionell bild för nyheten. Den återskapar inte verkliga personer och påstår inte att motivet visar händelsen. Om bildskapandet misslyckas används en tydligt märkt ämnesbild.</p></article></div></section>
    <section className="about-cta"><div className="page-wrap"><Clock3 /><div><span className="eyebrow light">Uppdateras 00:00 och 12:00</span><h2>Se vad som går åt rätt håll.</h2><p>Utforska flödet eller delta i ett konstruktivt samtal.</p></div><div><Link className="button light" to="/">Läs nyheter</Link><Link className="button outline-light" to="/forum">Besök forumet</Link></div></div></section>
    <section className="quality-note page-wrap"><CheckCircle2 /><div><h2>Det här lovar vi inte ännu</h2><p>Ljusglimt ska inte beskrivas som en färdig redaktion, oberoende journalistik eller ett fullständigt faktagranskat flöde. Det är en transparent produkt under utveckling – och den skillnaden ska synas.</p></div></section>
  </>
}
