"""Link existing Z-Image webp files to articles in news.json.

All 48 webp files already exist on disk (generated by Z-Image pipeline), but 45
articles lack an ai_image block, so the site shows category fallback instead.
This writes proper ai_image blocks with correct sha256 and Z-format timestamps.
"""
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NEWS = ROOT / "data" / "news.json"
AI_DIR = ROOT / "public" / "news-images" / "ai" / "articles"
PREFIX = "/news-images/ai/articles/"

data = json.loads(NEWS.read_text(encoding="utf-8"))
items = data["items"] if isinstance(data, dict) else data
now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
linked = 0
for it in items:
    if it.get("ai_image"):
        continue  # already linked
    fp = it.get("source_fingerprint", it["id"][:20])
    fname = f"{it['id']}-{fp}-v1.webp"
    fpath = AI_DIR / fname
    if not fpath.exists():
        print(f"SKIP (no webp): {it['id'][:10]}")
        continue
    blob = fpath.read_bytes()
    it["ai_image"] = {
        "url": f"{PREFIX}{fname}",
        "alt": it.get("title", "Artikelbild"),
        "model": "comfyui-z-image-turbo",
        "prompt_version": "z-image-turbo-v1",
        "source_fingerprint": fp,
        "width": 1280,
        "height": 848,
        "sha256": hashlib.sha256(blob).hexdigest(),
        "generated_at": now,
    }
    linked += 1
NEWS.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Linked {linked} articles to their webp images.")
